services:
  server:
    image: nginx:latest
    container_name: course-nginx  
    restart: always
    ports: 
    - 8888:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./symfony/public/bundles:/app/public/bundles
    depends_on:
      - symfony
    networks:
      - symfony

  symfony:
    build: ./symfony
    container_name: course-symfony
    restart: always
    ports:
    - 9000:9000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # use bubdles from image
      - /app/public/bundles
      - ./symfony:/app
      # xdebug config
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - symfony


  frontend:
    build: ./frontend
    container_name: course-frontend
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
    - 3000:3000
    depends_on:
      - symfony
    networks:
      - symfony

  mysql:
    image: mysql
    container_name: course-mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: gnTsdl!32s
      MYSQL_DATABASE: course
    volumes:
    - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 20s
    networks:
      - symfony

volumes:
  mysql_data:

networks:
  symfony:
    name: symfony



